alias vi='nvim'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias rm='rm -Iv'
alias cl='clear'
alias py='python'
alias xdg='xdg-open'
alias ..='cd ../'
alias ...='cd ../../'
alias ls='ls -la --color=always'
alias lsd='find . -maxdepth 3 -not -path "*/\.*" -type d'
alias lsg='ls | grep'
export PS1='\u@\h:\[\e[33m\]\w\[\e[0m\]\$ '
