[cpu]
freqs_ghz = [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]
path_temp = ""
path_freq = ""
path_gov = ""

[cpu0]
freqs_ghz = [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]
path_temp = ""
path_freq = ""
path_gov = ""

[governor]
temp_limit_c = 75.0
thresh_up_perc = 80.0
thresh_down_perc = 70.0
