#!/bin/sh

. "$HOME/.xsessionrc"

case $1 in
"startxfce4")
    exec startxfce4
    ;;
"herbstluftwm"|*)
    setxkbmap -layout de -model pc105 -option terminate:ctrl_alt_bksp -option caps:none
    xsetroot -solid black -cursor_name left_ptr
    xset b off
    xset r rate 300 50
    redshift -PO 4000
    exec herbstluftwm
    ;;
esac
