#!/bin/sh

. "$HOME/.xsessionrc"

case $1 in
"startxfce4")
    exec startxfce4
    ;;
"herbstluftwm")
    setxkbmap -layout de -model pc105 -option terminate:ctrl_alt_bksp -option caps:none
    xsetroot -solid black -cursor_name left_ptr
    xset b off
    xset r rate 300 50
    redshift -PO 4000
    exec herbstluftwm
    ;;
"i3")
    setxkbmap -layout de -model pc105 -option terminate:ctrl_alt_bksp -option caps:none
    xsetroot -solid black -cursor_name left_ptr
    xset b off
    xset r rate 300 50
    redshift -PO 4000
    exec i3
    ;;
"ratpoison")
    setxkbmap -layout de -model pc105 -option terminate:ctrl_alt_bksp -option caps:none
    xsetroot -solid black -cursor_name left_ptr
    xset b off
    xset r rate 300 50
    redshift -PO 4000
    exec ratpoison
    ;;
"openbsd-cwm")
    setxkbmap -layout de -model pc105 -option terminate:ctrl_alt_bksp -option caps:none
    xsetroot -solid black -cursor_name left_ptr
    xset b off
    xset r rate 300 50
    redshift -PO 4000
    killall -q nextcloud; nextcloud &
    killall -q nm-applet; nm-applet &
    killall -q blueman-applet; blueman-applet &
    killall -q polybar; polybar top &
    exec openbsd-cwm
    ;;
"/usr/bin/notion"|*)
    setxkbmap -layout de -model pc105 -option terminate:ctrl_alt_bksp -option caps:none
    xsetroot -solid black -cursor_name left_ptr
    xset b off
    xset r rate 300 50
    redshift -PO 4000
    exec notion
    ;;
esac
