include("/home/pthrr/.config/meli/accounts.toml")

[pager]
pager_context = 0
sticky_headers = true

[notifications]
script = "notify-send"

[composing]
editor_command = '$EDITOR +/^$'

[shortcuts.general]
scroll_up = 'k'
scroll_down = 'j'
scroll_left = 'h'
scroll_right = 'l'
next_tab = 'T'
enter_command_mode = ':'
quit = 'q'

[shortcuts.listing]
scroll_up = 'k'
scroll_down = 'j'
next_page = 'C-f'
prev_page = 'C-b'
next_mailbox = 'J'
prev_mailbox = 'K'
next_account = 'l'
prev_account = 'h'
open_entry = "Enter"
exit_entry = 'q'
new_mail = 'm'
set_seen = 'n'
search = '/'
select_entry = 'V'
focus_left = "Left"
focus_right = "Right"

[shortcuts.pager]
scroll_up = 'k'
scroll_down = 'j'
page_up = 'C-b'
page_down = 'C-f'

[shortcuts.composing]
edit = 'e'
send_mail = 's'
scroll_up = 'k'
scroll_down = 'j'

[terminal]
use_color = false
