include("/home/pthrr/.config/meli/accounts.toml")

[pager]
pager_context = 0
sticky_headers = true

[notifications]
script = "notify-send"

[composing]
editor_command = '$EDITOR +/^$'

[shortcuts.general]
scroll_up = 'k'
scroll_down = 'j'
scroll_left = 'h'
scroll_right = 'l'
next_tab = 'T'
enter_command_mode = ':'
quit = 'q'

[shortcuts.listing]
scroll_up = 'k'
scroll_down = 'j'
next_page = 'C-f'
prev_page = 'C-b'
next_mailbox = 'J'
prev_mailbox = 'K'
next_account = 'l'
prev_account = 'h'
open_entry = "Enter"
exit_entry = 'q'
new_mail = 'm'
set_seen = 'n'
search = '/'
select_entry = 'V'
focus_left = "Left"
focus_right = "Right"

[shortcuts.pager]
scroll_up = 'k'
scroll_down = 'j'
page_up = 'C-b'
page_down = 'C-f'

[shortcuts.composing]
edit = 'e'
send_mail = 's'
scroll_up = 'k'
scroll_down = 'j'

[terminal]
use_color = true
theme = "terminal"

[terminal.themes.terminal]
"theme_default" = { fg = "Default", bg = "Default" }
"status.bar" = { fg = "Default", bg = "Default", attrs = "Bold" }
"status.command_bar" = { fg = "Default", bg = "Default" }
"status.notification" = { fg = "Default", bg = "Default", attrs = "Bold" }
"tab.focused" = { fg = "Default", bg = "Default", attrs = "Bold" }
"tab.unfocused" = { fg = "Default", bg = "Default" }
"tab.bar" = { fg = "Default", bg = "Default" }
"highlight" = { fg = "Default", bg = "Default", attrs = "Reverse" }
"mail.sidebar" = { fg = "Default", bg = "Default" }
"mail.sidebar_highlighted" = { fg = "Default", bg = "Default", attrs = "Reverse" }
"mail.sidebar_unread_count" = { fg = "Default", bg = "Default", attrs = "Bold" }
"mail.view.headers" = { fg = "Default", bg = "Default" }
"mail.view.headers_names" = { fg = "Default", bg = "Default", attrs = "Bold" }
"mail.view.headers_area" = { fg = "Default", bg = "Default" }
"mail.view.body" = { fg = "Default", bg = "Default" }
"mail.listing.compact.even" = { fg = "Default", bg = "Default" }
"mail.listing.compact.odd" = { fg = "Default", bg = "Default" }
"mail.listing.compact.even_unseen" = { fg = "Default", bg = "Default", attrs = "Bold" }
"mail.listing.compact.odd_unseen" = { fg = "Default", bg = "Default", attrs = "Bold" }
"mail.listing.compact.even_highlighted" = { fg = "Default", bg = "Default", attrs = "Reverse" }
"mail.listing.compact.odd_highlighted" = { fg = "Default", bg = "Default", attrs = "Reverse" }
"mail.listing.compact.even_selected" = { fg = "Default", bg = "Default", attrs = "Underline" }
"mail.listing.compact.odd_selected" = { fg = "Default", bg = "Default", attrs = "Underline" }
